const SUPABASE_URL='https://uobuxepixrqijgciurve.supabase.co';
const SUPABASE_KEY='sb_publishable_5cu-Flvr7CSvRPMT3hByMQ_CfO7mBIv';
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY)||null;
let products=[];let cart=[];let detailsQuantity=1;
try{cart=JSON.parse(localStorage.getItem('myCart'))||[]}catch{cart=[]}
const productId=Number(new URLSearchParams(location.search).get('id'));
const $=id=>document.getElementById(id);const productDetails=$('productDetails'),relatedProducts=$('relatedProducts');const cartCountElement=$('cartCount'),cartModal=$('cartModal'),cartBtn=$('cartBtn'),closeCartBtn=$('closeCartBtn'),cartItemsContainer=$('cartItemsContainer'),cartTotalPrice=$('cartTotalPrice'),checkoutBtn=$('checkoutBtn'),menuBtn=$('menuBtn'),mobileMenu=$('mobileMenu'),searchBtn=$('searchBtn');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function normalize(item){let sizes=item.sizes;if(typeof sizes==='string'){try{sizes=JSON.parse(sizes)}catch{sizes=[]}}if(!Array.isArray(sizes))sizes=[];return{id:Number(item.id),name:item.name||'',category:item.category||'',price:Number(item.price||0),oldPrice:item.old_price==null?null:Number(item.old_price),badge:item.badge||'',rating:5,sizes,image:item.image||'',description:item.description||''};}
async function loadProducts(){if(!supabaseClient){showToast('تعذر الاتصال بقاعدة البيانات');return}const{data,error}=await supabaseClient.from('products').select('*').order('id',{ascending:false});if(error){console.error(error);showNotFound('حدث خطأ أثناء تحميل المنتج');return}products=(data||[]).map(normalize);syncCart();renderProduct();renderRelated();}
function syncCart(){const ids=new Set(products.map(p=>p.id));cart=cart.filter(i=>ids.has(Number(i.id)));updateCartUI();}
function renderProduct(){if(!productDetails)return;const p=products.find(x=>x.id===productId);if(!p){showNotFound('المنتج غير موجود');return}document.title=`STEP | ${p.name}`;const sizes=p.sizes.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');productDetails.innerHTML=`<div class="product-details-grid"><div class="product-details-image">${p.badge?`<span class="product-details-badge">${esc(p.badge)}</span>`:''}<img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="product-details-info"><p class="product-details-category">${esc(p.category)}</p><h1>${esc(p.name)}</h1><div class="details-rating"><span>★★★★★</span><span>(5)</span></div><div class="details-price"><span class="details-current-price">${p.price} جنيه</span>${p.oldPrice?`<span class="details-old-price">${p.oldPrice} جنيه</span>`:''}</div><div class="details-divider"></div><p class="product-description">${esc(p.description||'لا يوجد وصف متاح لهذا المنتج.')}</p><div class="details-option"><label for="detailsSize">المقاس</label><select id="detailsSize" class="details-size-select"><option value="">اختر المقاس</option>${sizes}</select></div><div class="details-option"><label>الكمية</label><div class="details-quantity"><button id="detailsQuantityMinus" type="button">−</button><span id="detailsQuantity">1</span><button id="detailsQuantityPlus" type="button">+</button></div></div><button id="detailsAddButton" class="details-add-btn" type="button"><i class="fa-solid fa-bag-shopping"></i> إضافة للسلة</button><a href="index.html#products" class="back-products-btn"><i class="fa-solid fa-arrow-right"></i> العودة للمنتجات</a></div></div>`;$('detailsQuantityMinus').onclick=()=>changeDetailsQuantity(-1);$('detailsQuantityPlus').onclick=()=>changeDetailsQuantity(1);$('detailsAddButton').onclick=addProductToCart;}
function showNotFound(msg){if(productDetails)productDetails.innerHTML=`<div class="product-not-found"><h2>${esc(msg)}</h2><p>المنتج المطلوب غير متاح حاليًا.</p><br><a href="index.html#products">العودة للمنتجات</a></div>`;if(relatedProducts)relatedProducts.innerHTML='';}
function changeDetailsQuantity(change){detailsQuantity=Math.max(1,Math.min(20,detailsQuantity+change));if($('detailsQuantity'))$('detailsQuantity').textContent=detailsQuantity;}
function addProductToCart(){const p=products.find(x=>x.id===productId);if(!p)return;const size=$('detailsSize')?.value||'';if(!size){showToast('اختار المقاس الأول');$('detailsSize')?.focus();return}const old=cart.find(i=>i.id===p.id&&String(i.size)===String(size));if(old)old.quantity+=detailsQuantity;else cart.push({id:p.id,name:p.name,price:p.price,image:p.image,size,quantity:detailsQuantity});updateCartUI();showToast(`تمت إضافة ${p.name} مقاس ${size} للسلة`);}
function updateCartUI(){const ids=new Set(products.map(p=>p.id));cart=cart.filter(i=>ids.size===0||ids.has(Number(i.id)));cart.forEach(i=>i.quantity=Math.max(1,Number(i.quantity||1)));$('cartCount').textContent=cart.reduce((s,i)=>s+i.quantity,0);localStorage.setItem('myCart',JSON.stringify(cart));renderCart();}
function renderCart(){if(!cartItemsContainer)return;if(!cart.length){cartItemsContainer.innerHTML='<div class="cart-empty"><i class="fa-solid fa-bag-shopping"></i><p>السلة فارغة حاليًا</p></div>';cartTotalPrice.textContent='0 جنيه';return}let total=0;cartItemsContainer.innerHTML='';cart.forEach(i=>{const x=i.price*i.quantity;total+=x;const el=document.createElement('div');el.className='cart-item';const size=String(i.size).replaceAll("'","\\'");el.innerHTML=`<div class="cart-item-image" style="background-image:url('${esc(i.image)}')"></div><div class="cart-item-info"><h4>${esc(i.name)}</h4><div class="cart-item-size">المقاس: ${esc(i.size)}</div><div class="cart-item-price">${i.price} جنيه</div><div class="cart-controls"><button class="quantity-btn" type="button" onclick="changeCartQuantity(${i.id},'${size}',-1)">−</button><span class="quantity-value">${i.quantity}</span><button class="quantity-btn" type="button" onclick="changeCartQuantity(${i.id},'${size}',1)">+</button></div><button class="remove-item-btn" type="button" onclick="removeFromCart(${i.id},'${size}')">حذف المنتج</button></div>`;cartItemsContainer.appendChild(el)});cartTotalPrice.textContent=`${total} جنيه`}
function changeCartQuantity(id,size,c){const i=cart.find(x=>x.id===Number(id)&&String(x.size)===String(size));if(!i)return;i.quantity+=Number(c);if(i.quantity<=0)removeFromCart(id,size);else updateCartUI()}
function removeFromCart(id,size){cart=cart.filter(i=>!(i.id===Number(id)&&String(i.size)===String(size)));updateCartUI();showToast('تم حذف المنتج من السلة')}
function renderRelated(){if(!relatedProducts)return;const current=products.find(p=>p.id===productId);const list=products.filter(p=>p.id!==productId&&(!current||p.category===current.category)).slice(0,4);const final=list.length?list:products.filter(p=>p.id!==productId).slice(0,4);relatedProducts.innerHTML=final.map(p=>`<div class="product-card"><a href="product.html?id=${p.id}" class="product-image-link"><div class="product-image"><img class="product-image-inner" src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy">${p.badge?`<span class="product-badge">${esc(p.badge)}</span>`:''}</div></a><div class="product-info"><div class="product-category">${esc(p.category)}</div><a href="product.html?id=${p.id}"><h3>${esc(p.name)}</h3></a><div class="product-rating">★★★★★</div><div class="price-box"><span class="product-price">${p.price} جنيه</span>${p.oldPrice?`<span class="old-price">${p.oldPrice} جنيه</span>`:''}</div><a href="product.html?id=${p.id}" class="add-to-cart" style="display:flex;align-items:center;justify-content:center">عرض المنتج</a></div></div>`).join('')}
function showToast(message){document.querySelector('.toast-notification')?.remove();const t=document.createElement('div');t.className='toast-notification';t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.classList.add('show'),30);setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),300)},2500)}
function openCart(){cartModal?.classList.add('open');document.body.classList.add('cart-open')}function closeCart(){cartModal?.classList.remove('open');document.body.classList.remove('cart-open')}
function checkout(){if(!cart.length){showToast('السلة فارغة. أضف حذاء أولًا');return}let msg='مرحبًا، أريد إتمام طلب شراء من STEP\n\n',total=0;cart.forEach((i,n)=>{const x=i.price*i.quantity;total+=x;msg+=`${n+1}. ${i.name}\nالمقاس: ${i.size}\nالكمية: ${i.quantity}\nالسعر: ${i.price} جنيه\nالإجمالي: ${x} جنيه\n\n`});msg+=`الإجمالي الكلي: ${total} جنيه\n\nأريد تأكيد الطلب.`;window.open(`https://wa.me/201060722464?text=${encodeURIComponent(msg)}`,'_blank')}
function search(){const q=prompt('اكتب اسم الحذاء أو القسم');if(!q)return;const n=q.trim().toLowerCase();const found=products.filter(p=>p.name.toLowerCase().includes(n)||p.category.toLowerCase().includes(n));if(!found.length){showToast('لم يتم العثور على المنتج');return}renderRelatedSearch(found)}
function renderRelatedSearch(list){if(!relatedProducts)return;relatedProducts.innerHTML=list.slice(0,8).map(p=>`<div class="product-card"><a href="product.html?id=${p.id}" class="product-image-link"><div class="product-image"><img class="product-image-inner" src="${esc(p.image)}" alt="${esc(p.name)}"></div></a><div class="product-info"><div class="product-category">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="price-box"><span class="product-price">${p.price} جنيه</span></div><a href="product.html?id=${p.id}" class="add-to-cart" style="display:flex;align-items:center;justify-content:center">عرض المنتج</a></div></div>`).join('');relatedProducts.closest('.related-products')?.scrollIntoView({behavior:'smooth'})}
function goToCategory(category){sessionStorage.setItem('stepCategory',category)}
cartBtn?.addEventListener('click',openCart);closeCartBtn?.addEventListener('click',closeCart);cartModal?.addEventListener('click',e=>{if(e.target===cartModal)closeCart()});checkoutBtn?.addEventListener('click',checkout);menuBtn?.addEventListener('click',()=>mobileMenu?.classList.toggle('open'));mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileMenu.classList.remove('open')));searchBtn?.addEventListener('click',search);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});
window.goToCategory=goToCategory;window.changeCartQuantity=changeCartQuantity;window.removeFromCart=removeFromCart;
document.addEventListener('DOMContentLoaded',loadProducts);
